### ISSUE TITLE
docker way

### ISSUE THREAD

**Issue by clement-igonet** [morph-labs/rift#233]
As a first step to go to docker world, to avoid to manage pyenv, I suggest a Dockerfile for rift-engine:
```
FROM python:3.10.13-bookworm
WORKDIR /rift-engine
COPY . /rift-engine
RUN pip install -e .
```

And then a `docker-compose.yml` file:
```
version: '3.9'

services:
  rift-engine:
    build:
      context: ./rift/rift-engine
      dockerfile: Dockerfile
```

Then, here are command to build:
`docker compose build rift-engine`
